### ISSUE TITLE
feat: minor inconvenience when downloading updates

### ISSUE THREAD

**Issue by AnonymouseHucker29** [ReVanced/revanced-manager#1047]
### Type

Functionality

### Issue

The bug only occurs when there's a manager update.

- Open Revanced Manager
- Tap on Update
- After the download is done, the app automatically installs the apk.
 If this is the case, then it defeats the purpose of the dialog box after the installation which prompts the user whether to install the apk or not.

### Feature

Remove the auto install function after the download is finished since there is a dialog box that will prompt the user to install the update

### Motivation

It's more of an inconvenience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
Can you share a screen recording of how the installation is happening automatically? Manager updates are never installed silently even if you are rooted.

**Comment by AnonymouseHucker29** [comment]
> Can you share a screen recording of how the installation is happening automatically? Manager updates are never installed silently even if you are rooted.

I'll try when new update comes

**Comment by TheAabedKhan** [comment]
>I'll try when new update comes

You can download any previous versions of the manager and then record the update issue you are facing.

**Comment by ILoveOpenSourceApplications** [comment]
Is your issue similar to that of #1030?

**Comment by TheAabedKhan** [comment]
>Is your issue similar?

No, that issue is about not getting the installation result. This issue is related to not even getting the installation prompt.

**Comment by TheAabedKhan** [comment]
@AnonymouseHucker29 you are requested to either update or close this issue.

**Comment by AnonymouseHucker29** [comment]
Apologies for the late response.

Anyways, you can see in the screen record that after downloading, there's a toast which says installing update and even if I didn't tap on it, something would pop up (package installer) before even reaching the revanced dialog which asks the user to install the update or not.

https://github.com/ReVanced/revanced-manager/assets/92257095/f555c672-49f1-4936-afb6-9e1edd03f9ca

**Comment by TheAabedKhan** [comment]
That's the default behavior. The `Installing update` toast appears to inform users that the Android is now going to launch the Package installer to install the downloaded apk, and because you have multiple apps that can handle the package installer intent, you are asked to select the one you want to use. In the video, you chose the built-in Package Installer app, and the sudden dialog that's appearing is the Package Installer window staging your app to install. Staging took less than a second, so the dialog disappeared immediately.

Conclusion: The app is not updated unless you hit install from the Package Installer dialog.
