### ISSUE TITLE
Youtube patcher not working anymore

### ISSUE THREAD

**Issue by batata004** [ReVanced/revanced-manager#1053]
### Type

Error while running the manager

### Bug description

I've been using Revanced Manager to patch youtube since the beginning of this app, and it worked fine most of the time. However yesterday I already tried patching youtube in at least 2 devices (Samsung A52 and Xiaomi A3 both not rooted) and it gets aborted in the middle.

I am using the DEFAULT patches and I am using the latest Youtube version on APK MIRROR - 18.27.35. Also, this is something I cant understand: it looks like Revanced Manager only works with specific versions of Youtube (downloaded from APK MIRROR) however I see no official documentation where you say which versions the users should try (or at least the latest compatible version).

Maybe, if you could tell me the latest youtube version that I should download from APK MIRROR I could give it a try and tell you if it works. Also, I just want to block ads and use sponsor block, do I really need to select all the options inside DEFAULT? Maybe there should be a minimal PATCH option that only block ads and enable sponsor block, which is what most people are looking for.

### Steps to reproduce

Use reavnced manager to patch the latest youtube apk 18.27.35 with DEFAULT patches.

### Android version

Latest on both devices

### Manager version

Latest on both devices

### Target package name

Youtube 18.27.35

### Target package version.

youtube 18.27.35

### Installation type

Non-root

### Patches selected.

All the DEFAULT

### Device logs (exported using Manager settings).

```shell
I dont have it
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by zainkhas** [comment]
I can confirm this. Same happens for me on my Pixel 5 (Stock) and Redmi Note 9 Pro (Pixel Experience Plus).

Here are the logs

`Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Custom branding
Applied Disable zoom haptics
Applied Enable debugging
Failed to apply Hide player overlay: Failed to resolve CreatePlayerOverviewFingerprint
Applied Premium heading
Applied Theme
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~5lE9vdeP0GoWy39rne0ZXA==/app.revanced.manager.flutter-4rfMNYJ8zCQUxqrbGlvTzw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1538776512, --version-name, 18.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3376639154081955505.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~5lE9vdeP0GoWy39rne0ZXA==/app.revanced.manager.flutter-4rfMNYJ8zCQUxqrbGlvTzw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1538776512, --version-name, 18.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3376639154081955505.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WBZGLA/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
`

**Comment by oSumAtrIX** [comment]
Using incorrect version/Dupe issue

**Comment by batata004** [comment]
> Using incorrect version/Dupe issue

So what is the correct version??

**Comment by TheAabedKhan** [comment]
>So what is the correct version??

Use the suggested version, right now it's 18.23.35

**Comment by batata004** [comment]
> > So what is the correct version??
> 
> Use the suggested version, right now it's 18.23.35

That's exactly the version that is generating this error.

**Comment by TheAabedKhan** [comment]
> That's exactly the version that is generating this error.

![Screenshot_20230727-200508_Pixel Launcher Extended~2.png](https://github.com/ReVanced/revanced-manager/assets/39409020/1e9f173d-e575-43d5-bf4e-ecd09f6c990a)

This is what you have mentioned.

**Comment by batata004** [comment]
@TheAabedKhan Thank you so much! You are indeed correct, I am using the wrong version. But I have a question to ask: is there a  place in the documentation (here on gitbhub) where you say the latest compatile version? I can find a place that suggests the version 18.23.35 as the correct one to use with the Revanced Manager.

**Comment by TheAabedKhan** [comment]
@batata004 You can check the suggested version of any supported apps on the official ReVanced website, https://revanced.app/patches. Select any app and you can see all the available patches for the apps too.

**Comment by batata004** [comment]
@TheAabedKhan AWESOME!!! THANKS!
