### ISSUE TITLE
Use a different app icon from ReVanced YouTube app

### ISSUE THREAD

**Issue by Hexaae** [ReVanced/revanced-manager#1131]
### Type

Cosmetic

### Issue

Has the same icon of ReVanced YouTube.

### Feature

Please, use a different icon image for ReVanced Manager.

### Motivation

Just to distinguish the two apps on the fly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Open this issue in the ReVanced Patches repository, it's only expected of the ReVanced Manager to use the ReVanced icon.

**Comment by infinitewaveparticle** [comment]
@Ushie I use a firewall app called AdGuard and in its filtering log it shows only the icons of the apps that are connecting to the internet. As such I can't tell which app is which (ReVanced Manager or YouTube ReVanced) without opening each connection's details. It would be nice if you could slightly change the icon of one app or the other so that they're distinguishable. Even just adding a small word or letter would help. I'm not an icon designer so I'd leave this up to you, but it really seems odd to have two apps with exactly the same icon. Thank you.

**Comment by Ushie** [comment]
Please include the Custom Branding patch, make sure to click on the settings icon of the patch to set it to the ReVanced icon

**Comment by Ushie** [comment]
@infinitewaveparticle I slightly misunderstood you, do you not have app names enabled?

Nevertheless, you can disable the Custom Branding patch and the icon will stay as YouTube, you won't mistake it for ReVanced Manager

**Comment by infinitewaveparticle** [comment]
It's really only an issue in my firewall app, but like you said I can just cut out the custom branding. I still believe it to be best practices to use 1 icon per package tho. Thank you!

Sent from Proton Mail mobile

-------- Original Message --------
