### ISSUE TITLE
YouTube ReVanced Keep Crashing

### ISSUE THREAD

**Issue by Parsa307** [revanced/revanced-manager#127]
### Type

Other

### Branch

no

### Bug description

Youtube ReVanced Keep Crashing

### Steps to reproduce

I Download YouTube ReVanced Apk In Apkmirror
And Use ReVanced Manager To Patch

### Relevant log output

```shell
I Dont Have log
```

**Comment by Parsa307** [comment]
I Download YouTube in apkmirror
Not ReVanced

**Comment by SadLinusGuy0** [comment]
What version of YouTube have you downloaded? I can't upgrade any higher
that v17.33.42

**Comment by Alprnn357** [comment]
@Parsa307 
YT ReVanced crashes because you don't have microg services installed.
Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases) to fix the issue.

**Comment by CodeIsFunNyk** [comment]
> Need logs. make sure you installed full yt apk (130mb+) and version 17.33.42.

I can't even select yt app from my storage in revanced apk i have exactly the same version that you mentioned

**Comment by MinorX** [comment]
I've been facing the same issue. 
My logs are :- 

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'resource-id-mapping-provider-resource-patch-dependency' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-infocard-suggestions' of type: bytecode
[success] hide-infocard-suggestions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
[success] downloads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'seekbar-tapping' of type: bytecode
[success] seekbar-tapping
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'player-type-hook' of type: bytecode
Skipping 'settings' because it has already been applied
Executing 'swipe-controls-resource-patch' of type: resource
Executing 'swipe-controls' of type: bytecode
[success] swipe-controls
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-captions' of type: bytecode
[success] disable-auto-captions
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'hide-autoplay-button' of type: bytecode
[success] hide-autoplay-button
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
[error] premium-heading:app.revanced.patcher.patch.PatchResultError: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DSXEVU/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Skipping 'locale-config-fix' because it has already been applied
Executing 'custom-branding' of type: resource
[success] custom-branding
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-cast-button' of type: bytecode
[success] hide-cast-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-fullscreen-panels' of type: bytecode
[success] disable-fullscreen-panels
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
[success] old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-create-button' of type: bytecode
[success] hide-create-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-shorts-button' of type: bytecode
[success] hide-shorts-button
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
[success] return-youtube-dislike
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
[success] sponsorblock
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'tablet-mini-player' of type: bytecode
[success] tablet-mini-player
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
[success] theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
[success] hide-watermark
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-wide-searchbar' of type: bytecode
[success] enable-wide-searchbar
Skipping 'integrations' because it has already been applied
Executing 'always-autorepeat' of type: bytecode
[success] always-autorepeat
Executing 'client-spoof' of type: bytecode
[success] client-spoof
Skipping 'integrations' because it has already been applied
Executing 'custom-playback-speed' of type: bytecode
[success] custom-playback-speed
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hdr-auto-brightness' of type: bytecode
[success] hdr-auto-brightness
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings-resource-patch' because it has already been applied
Executing 'microg-resource-patch' of type: resource
Skipping 'hide-cast-button' because it has already been applied
Skipping 'client-spoof' because it has already been applied
Executing 'microg-support' of type: bytecode
[success] microg-support
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
[success] minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
[success] remember-video-quality
Skipping 'settings' because it has already been applied
[success] settings
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
[success] custom-video-buffer
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using nonroot method
Installed!

Screenshot of the error page :- 
![Screenshot_20220918_172048](https://user-images.githubusercontent.com/90025330/190902910-f7bf22f7-eb70-40ff-a66f-fc72e92fe7ca.jpg)

**Comment by MinorX** [comment]
And yes, I have micro-g and updated YT application.

**Comment by pietryszak** [comment]
> And yes, I have micro-g and updated YT application.

What android version do you use?

**Comment by MinorX** [comment]
> > And yes, I have micro-g and updated YT application.
> 
> What android version do you use?

12

**Comment by pietryszak** [comment]
> > > And yes, I have micro-g and updated YT application.
> > 
> > 
> > What android version do you use?
> 
> 12

And you download YT full apk from apk mirror yes?

**Comment by MinorX** [comment]
> > > > And yes, I have micro-g and updated YT application.
> > > 
> > > 
> > > What android version do you use?
> > 
> > 
> > 12
> 
> And you download YT full apk 17.36 from apk mirror yes?

No I didn't. Plus I don't think that you can select an .apk file directly for patching. Can we?

**Comment by pietryszak** [comment]
> > > > > And yes, I have micro-g and updated YT application.
> > > > 
> > > > 
> > > > What android version do you use?
> > > 
> > > 
> > > 12
> > 
> > 
> > And you download YT full apk 17.36 from apk mirror yes?
> 
> No I didn't. Plus I don't think that you can select an .apk file directly for patching. Can we?

@ponces You really shoud add better README.md. Including a prerequisites. Microg in mandatory, android 8 is mandatary. This could help avoid a bug duplicates.

**Comment by pietryszak** [comment]
> > > > > And yes, I have micro-g and updated YT application.
> > > > 
> > > > 
> > > > What android version do you use?
> > > 
> > > 
> > > 12
> > 
> > 
> > And you download YT full apk 17.36 from apk mirror yes?
> 
> No I didn't. Plus I don't think that you can select an .apk file directly for patching. Can we?

full apk from apk mirror is mandatory

**Comment by MinorX** [comment]
> > > > > > And yes, I have micro-g and updated YT application.
> > > > > 
> > > > > 
> > > > > What android version do you use?
> > > > 
> > > > 
> > > > 12
> > > 
> > > 
> > > And you download YT full apk 17.36 from apk mirror yes?
> > 
> > 
> > No I didn't. Plus I don't think that you can select an .apk file directly for patching. Can we?
> 
> full apk from apk mirror is mandatory

I'm so sorry. Yeah after using an apk from ApkMirror. It worked. I was just blind to notice STORAGE option in the select app .
Thanks 👉👈
