### ISSUE TITLE
bug: app scalng on tablet's Desktop mode doesn't work

### ISSUE THREAD

**Issue by Manifoldme** [ReVanced/revanced-manager#1317]
![20230925_222103](https://github.com/ReVanced/revanced-manager/assets/46833578/21996c7b-a4f8-4b18-8cf2-391733683b40)
### Bug description

Hardware: Lenovo Tab P11 Pro
OS: Android 12
Unpatched/Original YouTube app has a tablet mode and the full screen button works.
Pached app is loosing the ability to scale and opens in phone mode on an external monitor, the full screen button doesn't work anymore.
Tryed the tablet and mini tablet patches install with/without, on/off no changes 

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager: 1.10.3
YouTube 18.32.39

### Installation type

Non-root

**Comment by Ushie** [comment]
This isn't related to ReVanced Manager, and you removed the acknowledgements

**Comment by Manifoldme** [comment]
> This isn't related to ReVanced Manager, and you removed the acknowledgements

Wow. Rude, but alright.
And what does this problem relate to?

Concerning "acknowledgements", 
sorry, don't understand what do you mean, and how is it relevant to my still unanswered question.

**Comment by validcube** [comment]
> @Manifoldme Wow. Rude, but alright. And what does this problem relate to?

👋 Hello *sorry about that*! Your issue was closed because you've opened the issue in the ReVanced Manger's repository, unfortunately ReVanced Manager only manage and patch application using ReVanced Patches.

You should open an issue at the [ReVanced Patches' repository](https://github.com/ReVanced/revanced-patches/issues/new?assignees=&labels=bug&projects=&template=bug-issue.yml&title=bug(youtube)%3A+app+scaling+on+tablet%27s+Desktop+mode+doesn%27t+work) instead.
