### ISSUE TITLE
bug: Manager v1.10.3 & below keeps crashing upon opening 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1339]
### Bug description

After the release of ReVanced Manager v1.11.0, previous versions before this one started crashing upon opening making the app unusable and not possible to update the manager via the manager.

It's also after the user allows/denies permission to download the patches.

https://github.com/ReVanced/revanced-manager/assets/117499019/11a029e8-0e25-4d08-a233-7f35c7bbc6cb

### Version of ReVanced Manager and version & name of application you tried to patch

v1.10.3 & below 

### Installation type

Non-root

### Device logs

```shell
Nil
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Thank for reporting this bug,

Unfortunately, due to changes in ReVanced Patcher the manager now crashed with the exception of `java.lang.IncompatibleClassChangeError`

Right now, the best we could is to tell the user to compile their own 1.10.3 with the repository set to their desire one.

Apologies for any inconvenience. 

<details>
<summary>In case you're interested in compiling your own 1.10.3</summary>

# 🛠️ Building from source

This page will guide you through building ReVanced Manager from source.

1. Setup the Flutter environment for your [platform 🡕](https://docs.flutter.dev/get-started/install)

2. Clone the repository

   ```sh
   git clone https://github.com/revanced/revanced-manager.git && cd revanced-manager
   ```

3. Checkout the ReVanced Manager v1.10.3

   ```sh
   git checkout v1.10.3
   ```

4. Create a GitHub personal access token with the `read:packages` scope [here](https://github.com/settings/tokens/new?scopes=read:packages&description=ReVanced)

5. Add your GitHub username and the token to `~/android/gradle.properties`

   ```properties
   gpr.user = YourUsername
   gpr.key = ghp_longrandomkey
   ```

6. Get dependencies

   ```sh
   flutter pub get
   ```

7. Delete conflicting outputs

   ```sh
   flutter packages pub run build_runner build --delete-conflicting-outputs
   ```

   > **[!NOTE]**: Must be run every time you sync your local repository with the remote repository.

8. Build the APK

   ```sh
   flutter build apk
   ```

</details>

**Comment by validcube** [comment]
👋 Thank for reporting this bug,

Unfortunately, due to changes in ReVanced Patcher the manager now crashed with the exception of `java.lang.IncompatibleClassChangeError`

Right now, the best we could is to tell the user to compile their own 1.10.3 with the repository set to their desire one.

Apologies for any inconvenience. 

<details>
<summary>In case you're interested in compiling your own 1.10.3</summary>

# 🛠️ Building from source

This page will guide you through building ReVanced Manager from source.

1. Setup the Flutter environment for your [platform 🡕](https://docs.flutter.dev/get-started/install)

2. Clone the repository

   ```sh
   git clone https://github.com/revanced/revanced-manager.git && cd revanced-manager
   ```

3. Checkout the ReVanced Manager v1.10.3

   ```sh
   git checkout v1.10.3
   ```

4. Create a GitHub personal access token with the `read:packages` scope [here](https://github.com/settings/tokens/new?scopes=read:packages&description=ReVanced)

5. Add your GitHub username and the token to `~/android/gradle.properties`

   ```properties
   gpr.user = YourUsername
   gpr.key = ghp_longrandomkey
   ```

6. Get dependencies

   ```sh
   flutter pub get
   ```

7. Delete conflicting outputs

   ```sh
   flutter packages pub run build_runner build --delete-conflicting-outputs
   ```

   > **[NOTE]**: Must be run every time you sync your local repository with the remote repository.

8. Build the APK

   ```sh
   flutter build apk
   ```

</details>

**Comment by KobeW50** [comment]
> Right now, the best we can do is to tell the user to compile their own 1.10.3 with the repository set to their desire one.

Can't you open the Manager in airplane mode, change the sources, and then reopen while connected to the internet?

**Comment by validcube** [comment]
> > Right now, the best we can do is to tell the user to compile their own 1.10.3 with the repository set to their desire one.
> 
> Can't you open the Manager in airplane mode, change the sources, and then reopen while connected to the internet?

That could work, I haven't try it yet.

**Comment by ILoveOpenSourceApplications** [comment]
How unfortunate. Guess that means the user will either have to do the above mentioned workaround or will have to update by downloading the latest version from the internet.

**Comment by ILoveOpenSourceApplications** [comment]
But shouldn't we be avoiding such situations from happening in the future?

**Comment by validcube** [comment]
> But shouldn't we be avoiding such situations from happening in the future?

I believe that it should be fixed in v1.11.0, but I haven't check it.

Feels free to open an issue about it.

**Comment by KobeW50** [comment]
Yeah, it was fixed according to osum in this comment https://github.com/ReVanced/revanced-manager/issues/1330#issuecomment-1747871228

**Comment by ILoveOpenSourceApplications** [comment]
Yes. It's fine after 1.11.0 but what I meant is, in the next version release, let's say 1.12.0 as an example, the same scenario repeats due to bump in dependency/ breaking change. This situation shouldn't occur.

**Comment by KobeW50** [comment]
> Yes. It's fine after 1.11.0 but what I meant is, in the next version release, let's say 1.12.0 as an example, the same scenario repeats due to bump in dependency/ breaking change. This situation shouldn't occur.

If I understand osum's comment correctly, if this exact scenario were to occur again in the future, the manager will simply not store the new patches and will not crash.

However, you are certainly correct that the team should be more cautious and prepare for breaking changes such as what happened this time. Imo there should've been an update before 1.11.0 to prepare older manager versions so that they wont crash.
