### ISSUE TITLE
'Enable changing (patches) selection' toggle should also control Patch Options edits 

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1361]
### Feature description

When the 'Enable changing (patches) selection' toggle is disabled, the user should be prevented from configuring patch options. 

Alternatively, there should be a separate toggle to control whether patch options can be configured.

### Motivation

If the user is being protected from themselves by blocking their ability to customize the patches (so they won't make a critical mistake), the patch options should also be off limits since it is more advanced than simply selecting which patches.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
> the patch options should also be off limits

Some patches may even be used by default, options required, not set by default and changing the patches selection disabled. However, the user still has to configure the opportunity to be able to patch because the patch is enabled and the option unset but required (Select Sync for Reddit to understand).

There is no reason to prevent setting options regardless, as the "protection" you refer to above only is needed for patching the app, which options do not, but patches do. Thanks regardless.

**Comment by KobeW50** [comment]
Thats a great point. Thanks
