### ISSUE TITLE
Manager is down again

### ISSUE THREAD

**Issue by Malfaust** [ReVanced/revanced-manager#1445]
### Bug description

Please fix the Manager again

### Version of ReVanced Manager and version & name of application you tried to patch

1.14.2

### Installation type

None

### Device logs

```shell
None
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Thanks for your issue, but unfortunately, this issue is out of scope for ReVanced Manager.

The problem came when the API is unresponsive or down. Please be patient as the API team will try to restore the API.

Thank you for understanding! :)

![image](https://github.com/ReVanced/revanced-manager/assets/93124920/5fdc6d05-f5cf-47fa-9708-335727d6460c "Failure 523")
