### ISSUE TITLE
bug: Patch Bundles are unavailable for the first few moments after opening the app

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-manager#1502]
### Bug description

After opening the app, the UI loads completely but the app is not yet ready for use, although the Main Patch Bundle has been downloaded previously, and is locally available (presumably), it is not yet ready for use and the "Invalid" icon is shown on the Patch Bundle

This interrupts the user unnecessarily, as they can be moved to the Patch Bundle screen for no reason when they try to click "Add", and don't know what step to take next

https://github.com/ReVanced/revanced-manager/assets/79272171/7b05456c-e3c9-4366-9251-882fe6654b7e

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Axelen123** [comment]
We could try adding [`createdAtStart()`](https://github.com/ReVanced/revanced-manager/blob/bd9778a3d16ff7e97c65660045711a8e00923c04/app/src/main/java/app/revanced/manager/di/RepositoryModule.kt#L15) to the [`PatchBundleRepository`](https://github.com/ReVanced/revanced-manager/blob/bd9778a3d16ff7e97c65660045711a8e00923c04/app/src/main/java/app/revanced/manager/di/RepositoryModule.kt#L21) declaration. This will make the app load patch bundles when the app starts instead of waiting for `MainActivity` to inject the repository.
I don't think there is much else we can do to speed it up.

**Comment by Axelen123** [comment]
The solution has been implemented in https://github.com/ReVanced/revanced-manager/commit/9cab91959e85808317342084aafb821247813b68. I can tell there is a noticeable difference.

Reopen this issue if the problem persists.
