### ISSUE TITLE
bug: package conflicts with existing package

### ISSUE THREAD

**Issue by xlaxplaya** [ReVanced/revanced-manager#1579]
### Bug description

Getting a message that "package conflicts with existing package" even though youtube updates are uninstalled and the app is disabled. I'm on an unrooted Galaxy S23, so I can't fully uninstall the Youtube app; I can only disable it. **This bug is happening recently after I updated to OneUI 6.0, or Android 14.** I've never run into it before.

Things I've tried:
- My usual method: Completely disable Youtube, patch the APK, and then install the patched APK
- Another method: 1) Install unpatched APK, 2) patch the installed app from Manager, 3) remove updates from youtube, 4) disable youtube, and 5) install patched APK
- Disable Play Protect
- Tested different Youtube versions, v18.45.41 and v18.45.43, with same results
- Saving the APK and installing from the file browser, rather than within ReVanced.
- Tried reducing patches to only 5, logs below
- Uninstall everything (MicroG, ReVanced, and patched apps), reinstall ReVanced and try the whole thing again.

Related bug: ReVanced Manager doesn't show me any indicator or progress after hitting "Install". The install just fails silently and I'm left wondering what's going on for several minutes. Only by installing via Samsung's "My Files" browser do I get the error message about conflicting with an existing package.

[revanced-manager_logcat_20231218193444425029.log](https://github.com/ReVanced/revanced-manager/files/13709824/revanced-manager_logcat_20231218193444425029.log)

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced: 1.17.3
Youtube: 18.45.41 and 18.45.43

### Installation type

Non-root

### Device logs

```shell
.log file attached, it exceeded max character length
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-S911U1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.41 (Suggested: v18.45.43)
Patches version: v3.1.0
Patches added: Change package name [Package name: Default], Hide ads, Minimized playback, SponsorBlock, Video ads
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support [GmsCore Vendor: com.mgoogle], Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by GlenMerlin** [comment]
Have you tried adding the custom branding patch? that's what fixed this issue for me on my Pixel where I also can't uninstall YouTube

**Comment by xlaxplaya** [comment]
> Have you tried adding the custom branding patch? that's what fixed this issue for me on my Pixel where I also can't uninstall YouTube

Thanks for the suggestion, I just tried with the same results. Patch log attached.

[revanced patch log with custom branding.txt](https://github.com/ReVanced/revanced-manager/files/13710890/revanced.patch.log.with.custom.branding.txt)

**Comment by KobeW50** [comment]
The issue here isn't a bug, but rather either lies in the patch selection or has to do with an existing patched YouTube that is installed which is blocking the new installation. 

Please seek help in one of our support channels to resolve this issue.

**Comment by xlaxplaya** [comment]
Ah, GmsCore was it! Is that new? I don't think I've ever been required to add that patch before.

Either way, I'll close this issue. Thanks!

**Comment by MrEAlderson** [comment]
The issue is still present, even with GmsCore active. Tried both available options.
`- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-G996N
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43 (Suggested: v18.45.43)
Patches version: v3.1.0
Patches added: Alternative thumbnails, Bypass URL redirects, Change start page, Client spoof, Custom branding [App name: YouTube, App icon: ReVanced*Logo], Custom player overlay opacity, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable resuming Shorts on startup, Disable suggested video end screen, Enable slide to seek, Enable tablet layout, GmsCore support [GmsCore Vendor: app.revanced], HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide breaking news shelf, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide video action buttons, Minimized playback, Navigation buttons, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Remove tracking query parameter, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support [GmsCore Vendor: app.revanced], Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 49 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched`
It also doesn't matter if I use the default options with and without GmsCore

**Comment by KobeW50** [comment]
> The issue here isn't a bug, but rather either lies in the patch selection (missing `GmsCore support` patch) and/or has to do with an existing patched YouTube that is installed which is blocking the new installation. 
> 
> Please seek help in one of our support channels to resolve this issue.

@MrEAlderson

**Comment by RayAuxey** [comment]
I am facing a simmilar issue.
I have enabled GmsCore support but  the issue persists.
When I install the app via App Manager I get this error:
```
INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.youtube.revanced attempting to redeclare permission com.google.android.youtube.permission.C2D_MESSAGE already owned by com.google.android.youtube
```

**Comment by Ushie** [comment]
This repository is only about ReVanced Manager, please move to [the appropriate repository](https://github.com/ReVanced/revanced-patches)

**Comment by MrEAlderson** [comment]
> I am facing a simmilar issue while patching `Youtube v19.04.37`. I have enabled GmsCore support but the issue persists. When I install the app via App Manager I get this error:
> 
> ```
> INSTALL_FAILED_DUPLICATE_PERMISSION: 
> Package com.google.android.youtube.revanced attempting to redeclare permission
> com.google.android.youtube.permission.C2D_MESSAGE
> already owned by com.google.android.youtube
> ```
> 
> I cannot uninstall youtube but previous version of Youtube Revanced `(v18.38.44)` worked

Remove youtube from the secure folder

**Comment by RayAuxey** [comment]
> Remove youtube from the secure folder.
I am not using a Samsung phone, I am using Oneplus Nord 3. I have disabled the Youtube App.

**Comment by nicermak** [comment]
You Actually Don't need to delete youtube.
Just make the patched youtube with different package name.
Click on the patch list and search for "custom package name".
Click on the config icon and enter the package you like.
Click the save, done buttons.
And start patching.

**Comment by yukichigai** [comment]
> You Actually Don't need to delete youtube. Just make the patched youtube with different package name. Click on the patch list and search for "custom package name". Click on the config icon and enter the package you like. Click the save, done buttons. And start patching.

Custom package name doesn't fix it.

**Comment by 54437698** [comment]
> > You Actually Don't need to delete youtube. Just make the patched youtube with different package name. Click on the patch list and search for "custom package name". Click on the config icon and enter the package you like. Click the save, done buttons. And start patching.
> 
> You need to have Universal Patches enabled for this to show up, FYI
> 
> EDIT: Also this doesn't work. Still getting the Installation Conflict error, only now when clicking "OK" to uninstall the app it says "App not found". Revanced Manager 1.23.2, patching YouTube 19.47.53

Same issue here.

**Comment by RedrcknRbn** [comment]
This is also happening to me on Revanced Manager 1.24.0, Patches 5.28.0
I've tried custom branding and changing package name. Revanced claims there is a conflict.
I can't uninstall YouTube, but I have un-installed all updates that I can.
I am trying to download YouTube 20.12.46

**Comment by oSumAtrIX** [comment]
This is a user error. Use default manager settings

**Comment by RedrcknRbn** [comment]
> This is a user error. Use default manager settings

Default settings also return the same error

**Comment by oSumAtrIX** [comment]
Record a video showcasing your settings, patching and installing the app and how it conflicts
