### ISSUE TITLE
chore: Disable update check in pre-release version

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1655]
Self-explanatory... well open to suggestions.

**Comment by BenjaminHalko** [comment]
I think it should instead check for pre-release updates.

**Comment by oSumAtrIX** [comment]
Development builds are not meant to be used like that. They are used for manual testing unless the update functionality is supposed to be tested.

**Comment by BenjaminHalko** [comment]
Ah ok. I was treating dev builds as beta builds, but that makes sense.

**Comment by oSumAtrIX** [comment]
On a related topic to clarify what "beta builds" are. Most people abuse the dev branch as "beta" releases which works for the most part. Instead, everything that is deployed to the consumer, including beta builds are in fact full releases off the main branch. The key difference here is, that unlike traditionally, you don't just release a "stable" release, but also a "beta" release at the same time. The release assets for example would contain a stable build and a beta build which is slightly different and ships the beta code. As you can see, this is a controlled beta release through the main branch/production channel to the user instead of a dev branch release that is not meant to be touched by anyone but developers. The point of them being public is not to serve as beta builds, but for transparency reasons similar to why code is, which OSS is all about.
