### ISSUE TITLE
bug: Changelog flows into the status bar

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1741]
### Bug description

When the changelogs are lengthy, the manager let's the user scroll it over the entire phone and even into the status bar which doesn't look good.

https://github.com/ReVanced/revanced-manager/assets/117499019/cb38be54-e64d-4659-9142-6bfd0b0b04f3

### Version of ReVanced Manager and version & name of app you are patching

v1.19.1

### Installation method

Regular

### ReVanced Manager logs

```shell
Nil
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Domenic-MZS** [comment]
Hi 🤝 @ILoveOpenSourceApplications, I'm new on this codebase, and I do like to help Open Source projects a bit more...

 At first glance I think this issue seems to be on how the *Changelogs* draggable/scrollable sheet is invoked... Flutter (the framework in which this application is built) by default will create a sheet without doing any `safeArea`, causing it to overlap some system intrusions (like the Samsung A54 notch, etc) at the top, but I'm not totally sure if that's the case with the `Notification Bar` overlapping.

 I'll dive deeper into this, and maybe do the changes or add more info on the issue...

I'm leaving some (maybe) important attachments and references for myself here.

#### Resources
- [ReVanced Manager - Changelogs Code][revancedchangelogsinvoke]
- Flutter [showModalBottomSheet(...)][showmodaldocs] documentation.


[showmodaldocs]: https://api.flutter.dev/flutter/material/showModalBottomSheet.html#:~:text=The%20useSafeArea%20parameter,Defaults%20to%20false.
[revancedchangelogsinvoke]: https://github.com/ReVanced/revanced-manager/blob/dev/lib/ui/views/home/home_viewmodel.dart#L464-L474
