### ISSUE TITLE
bug: Changelog includes pre-releases

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1755]
### Bug description

The changelog includes pre-releases, as well as those, that are above your current version.

### Version of ReVanced Manager and version & name of app you are patching

1.19.1

### Installation method

None

### ReVanced Manager logs

```shell
-
```

### Patch logs

```shell
-
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
Is this still the case? I think with the latest release this isn't an issue anymore.

**Comment by oSumAtrIX** [comment]
It should still be the case, in the current situation it doesn't occur though.

**Comment by TheAabedKhan** [comment]
> The changelog includes pre-releases

Should we not show pre-releases changelog if the current version is not a pre-release or add a toggle to include the pre-releases or not show them in any condition?

> as well as those, that are above your current version.

But changelog is supposed to show the changelog up to the latest version so that user can decide whether they want to update the manager, no?
