### ISSUE TITLE
bug: idk keystore password

### ISSUE THREAD

**Issue by weiliang011** [ReVanced/revanced-manager#1800]
### Bug description

I was patching with piko sources, but there was missing some patches so i changed to revancify, in this is a different signaTure so i exported keystore from revanced manager but it has a password
One more thing: this is not a bug, but at the types said that it can be issues too

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager: 1.19.3
App: twitter/x

### Installation method

Regular

### ReVanced Manager logs

```shell
.
```

### Patch logs

```shell
No logs
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by weiliang011** [comment]
Whats the password?

**Comment by validcube** [comment]
👋 Hello, @weiliang011!

The default password for all of our generated keystore are literally secure passwords (literally).

See:
https://github.com/ReVanced/revanced-manager/blob/dev/lib%2Fservices%2Fmanager_api.dart#L45-L45

Also unfortunately, your issue does not fall in any of the guideline since we only accept actual issue not a question, I'm going to close this as not fixed.

But I agree that there should be a way to see keystore password, feel free to open a feature request.

**Comment by ttv20** [comment]
`s3cur3p@ssw0rd`
https://github.com/ReVanced/revanced-manager/blob/3da2b49dad594b749832271920184195806e3409/lib/services/manager_api.dart#L46
