### ISSUE TITLE
bug: A "Disable auto updates" warning is unnecessary for non-root devices

### ISSUE THREAD

**Issue by kitadai31** [ReVanced/revanced-manager#2013]
### Bug description

When I tap the "Install" button after patching is completed, a warning will appear.

> Warning
Disable auto updates for the patched app to avoid unexpected issues.

<img width="240" src="https://github.com/ReVanced/revanced-manager/assets/90122968/971e66f8-2c01-4b1b-9f6a-1b57887104bd">

This dialog only appears on non-root devices.
On rooted devices, "Select install type" dialog appears instead.

However, this warning is unnecessary for non-root users.
Because patched apps have a different signature than original apps and will not be updated automatically.
Of course, manual updating is also impossible.

Therefore, this dialog should be removed.
Providing users an unnecessary instruction will confuse them.

Removing this dialog might be related to resolving #2012

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager v1.20.1 (stable)

### Installation method

None

### ReVanced Manager logs

```shell
no logs
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
I remember seeing a lot of people asking for Change package name option because of playstore updater

**Comment by ILoveOpenSourceApplications** [comment]
#1628

**Comment by oSumAtrIX** [comment]
An app store could uninstall and install the update. The warning is necessary for non root users

**Comment by kitadai31** [comment]
Sorry, I missed the existing issue.
But rather than adding a checkbox to disable this warning, I believe it have to be removed completely for non-root.

@Ushie
Ah, so that's the reason for the warning?
Certainly, prompting such people to disable auto-update would satisfy them.
(They would be "Yay, I disabled the auto update, so I don't have to care that the app is being shown in the update list anymore!")

But it doesn't solve the problem of patched apps showing up in the Play Store update list, so I doubt it makes sense.

@oSumAtrIX
That's true indeed.
It is *technically* possible for an app store to uninstall an app with different signature and install the update.

But Play Store will never do that.
Uninstalling the app means that the appdata will be lost.
I’m confident that they would never delete user data without the user's consent.
(At least as part of updating an app.  I don't know about other featurea such as Google Play Protect.)

In fact, the app store has never behaved like that.
Then this warning concerns about a problem that doesn't exist in reality.
I don't think this is worth sacrificing simplicity.

**Comment by oSumAtrIX** [comment]
> But Play Store will never do that

Play store is not the only app store.

**Comment by kitadai31** [comment]
Does other stores have a privilege to uninstall the app automatically?

**Comment by oSumAtrIX** [comment]
I believe as long as they are the system app store, yes

**Comment by kitadai31** [comment]
Oh, I forgot there are devices that has another app store in the rom.

But I still doubt that there is an app store that will uninstall an app automatically just because it fails to update.
Have you ever heard of such an app store actually?  Or, is it a supposition?

**Comment by oSumAtrIX** [comment]
We are working agnostic to any app and in terms of Android an auto updating app store could update the app even if the signature miss matches. Even Play Store can uninstall and install if you manually force it afaik

**Comment by kitadai31** [comment]
> an auto updating app store could update the app even if the signature miss matches

As far as I know, Android won't allow it, even if it's a system app.

Using the CorePatch source code as a reference, I looked at the source code of Android that compares signatures when updating an app, and I didn't find any flags or other stuff to avoid comparing signatures.

[InstallPackageHelper.preparePackageLI()](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/InstallPackageHelper.java;l=1733;drc=c28964b60e08271b118ed58189db375c85eac14a) -> [SIgningDetails.checkCapability()](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/pm/SigningDetails.java;l=625;drc=c9e2739f96fc65801cae42ac33ad78c0750547e0) -> [hasCertificateInternal()](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/pm/SigningDetails.java;l=694)

Also, the Android docs article on third-party app stores states that apps with different signatures are incompatible and must be uninstalled in order to update:

>*Regardless of which approach you choose, Android treats apps without a matching application ID and signing key as incompatible. A user wishing to switch from one store to another will need to delete the installed app—which will delete all data associated with that app—and reinstall from the other store.*
https://developer.android.com/google/play/app-updates

---

> Even Play Store can uninstall and install if you manually force it afaik

No, if I attempt to manually update a re-signed app in the Play Store, Play Store will just show you a generic, unhelpful error message.
They don't even show an uninstall button there.

<img width="360" src="https://github.com/ReVanced/revanced-manager/assets/90122968/468cedb8-edfb-4cc4-9a34-9b86d67edb6f">

Additionally, and importantly, the Play Store does not attempt to auto update re-signed apps.
Over the last few days, I've installed re-signed apps, left auto-update on, and tested to see if they were auto updated.
The result was that the Play Store never attempted to auto-update those apps.  (Meanwhile, normal apps have been updated.)

**Comment by oSumAtrIX** [comment]
Other app stores could still auto update by reinstalling the app. The same can occur with PlayStore as stated in their ToS section "Updates"

**Comment by kitadai31** [comment]
If the basis for the warning is that section of the ToS, then disabling auto update will have no effect.

> *Update may be completed irrespective of your Update settings in Google Play or your Device.*

**Comment by oSumAtrIX** [comment]
Like I said multiple times already, Play Store is not the basis, thus neither it's ToS

**Comment by kitadai31** [comment]
@oSumAtrIX May I open a PR for this?

I can understand your opinion, but the "Disable auto updates" warning is causing actual problems.

- A Third-party app store may auto install an update by uninstalling a existing patched app. -> This is just a possibility. There are no actual cases yet.
- Users may be confused and misunderstand the warning. -> This is an actually confirmed issue. I saw this problem in Discord many times. I can even list up 10 actual instances now. The one is https://github.com/ReVanced/revanced-manager/issues/1628#issuecomment-1890764228
The "Installation cancelled" problem is making this problem even greater. Due to this confusing warning, user thinks that "Installation cancelled" is caused by the auto updates.

I believe it is more important to fix a problem that is actually happening now than a problem that possibly happens but have not been an actual problem.

>However, "Installation cancelled" issue will be fixed soon, so the confused users may be reduced.
Feel free to refuse this.

**Comment by Ushie** [comment]
Removing it is only a workaround, not a fix for what you have mentioned

Maybe "Installation failed" can fix the issue of the users misunderstanding, but can we differentiate between canceling and failing? and why does ReVanced Manager even fail to install in the first place?

**Comment by kitadai31** [comment]
It doesn't matter if it's "Installation failed" or "Installation cancelled".
This applies to all kinds of installation failures.
The problem is that this warning misleads the user into thinking that automatic updates are the reason for the installation failure.

Additionally, even if the installation does not fail, this extra dialog will ruin the user experience.

**Comment by mihailmariusiondev** [comment]
Why is this issue closed? It's preventing users from installing a patched app. 

- Device Info
ReVanced Manager: 1.24.0
Model: 23049PCD8G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v8.05.51 (Suggested: 8.05.51)
Patches version: v5.27.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 8 patches
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation canceled
Installing patched app
Installation canceled
Installing patched app
Installation canceled

It won't let me install a patched app, is this intended? I just Uninstalled both YouTube music and YouTube (no signs of existing app) and won't let me install it, here's what Perplexity says, nothing helped, please reopen:

You are seeing a warning that says: "Disable auto updates for the patched app to avoid unexpected issues." This is a common prompt when installing patched apps (such as those modified by ReVanced Manager), and it's meant to prevent the official app stores from overwriting your patched version with an official update, which could break the modifications or cause installation errors[1][2].

## What You Should Do

**1. Disable Auto Updates for the Patched App**
- Open the Google Play Store (or any other app store you use).
- Search for the app you just patched (e.g., YouTube, YouTube Music).
- Go to the app's page.
- Tap the three dots in the top right corner.
- Uncheck or disable "Enable auto update" for that app[2][3][4][5].

**2. If You See "Installation Canceled"**
- This can happen for several reasons, not always related to auto-updates:
  - The original app might still be installed. Try uninstalling the official version first.
  - There could be a conflict due to signatures (patched apps have a different signature and cannot be updated by the Play Store automatically, but conflicts can still happen if the original is present)[1].
  - Try restarting your device, closing the patcher app, and repeating the installation process[2].

**3. If You Want to Avoid Future Issues**
- Always keep auto-updates off for patched apps.
- Consider using a patch that changes the package name (if available), so the Play Store doesn't recognize it as the original app. This can further prevent accidental overwrites, but may require additional steps like installing microG for Google services[2].

## Summary Table

| Step                          | Action                                                                 |
|-------------------------------|------------------------------------------------------------------------|
| Disable auto updates (all apps)| Play Store > Profile > Settings > Network Preferences > Auto-update apps > Don’t auto-update apps[6][3] |
| Disable auto updates (single app) | Play Store > App page > Three dots > Uncheck "Enable auto update"[4][5]       |
| If installation fails         | Uninstall original app, restart device, retry installation[2]          |

## Additional Notes

- For most users, disabling auto-updates for just the patched app is enough.
- The warning itself is sometimes unnecessary for non-root users, as Play Store usually can't update patched apps with different signatures, but it's still good practice to disable auto-updates to avoid any potential issues[1].
- If you continue seeing "Installation canceled" even after disabling updates, ensure the original app is uninstalled and try the installation again[2].

You can now safely tap "Install" on the warning dialog after following these steps.

**Comment by oSumAtrIX** [comment]
This is a bug fixed in dev branch of ReVanced Manager. Restart the app

**Comment by BenjaminBrienen** [comment]
If it is still in a dev branch, shouldn't it be an open issue? The PR into main would close this *as completed*.

**Comment by Ushie** [comment]
This issue is not targetting that bug
