### ISSUE TITLE
bug: APK sharing multiple times not possible

### ISSUE THREAD

**Issue by traeu** [revanced/revanced-manager#215]
### Type

Other

### Branch

Flutter

### Bug description

After patching (and before or after installing apk out of the patching procedure, doesn't matter) sharing of the APK is only possible one time. If "Share APK" is pressed again (if you accidentally choose the wrong app for sharing or if you closed the sharing-popup accidentally at the first time) nothing happens.

Sharing Log file works multiple times. Every time I press "Share log", the sharing-popup appears.

### Steps to reproduce

1. select patches and start patching procedure, wait till its finished and asks to install.
2. use "Share APK" from the menu in the upper right corner. The standard android sharing popup appears and you can export the apk.
3. export the apk or close the sharing popup without sharing, does not matter
4. press "Share APK" again. Nothing happens.
5. bonus: click on install, wait till install is done
6. press "Share APK" again. Still nothing happens.

### Relevant log output

```shell
really needed for this?
```

**Comment by Krafting** [comment]
The problem seems to be about renaming the APK (once its renamed, the app won't be able to rename it again, as it no longer have the same name), here is some log when I click the Share APK button a second time:

`09-19 01:20:32.198 19025 23960 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot rename file to '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HJPROC/youtube-revanced_v17.36.37.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HJPROC/out.apk' (OS Error: No such file or directory, errno = 2)
09-19 01:20:32.198 19025 23960 E flutter : #0      _File.throwIfError (dart:io/file_impl.dart:635)
09-19 01:20:32.198 19025 23960 E flutter : #1      _File.renameSync (dart:io/file_impl.dart:320)
09-19 01:20:32.198 19025 23960 E flutter : #2      PatcherAPI.sharePatchedFile (package:revanced_manager/services/patcher_api.dart:202)
09-19 01:20:32.198 19025 23960 E flutter : #3      InstallerViewModel.shareResult (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:162)
09-19 01:20:32.198 19025 23960 E flutter : #4      InstallerViewModel.onMenuSelection (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:183)
09-19 01:20:32.198 19025 23960 E flutter : #5      InstallerView.build.<anonymous closure>.<anonymous closure> (package:revanced_manager/ui/views/installer/installer_view.dart:36)
09-19 01:20:32.198 19025 23960 E flutter : #6      PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart:1207)
09-19 01:20:32.198 19025 23960 E flutter : <asynchronous suspension>
`

**Comment by ponces** [comment]
Fixed on https://github.com/revanced/revanced-manager/commit/9405334a7db7a78ac24da008f3785598c8a8ecd1.
Thanks!
Closed.
