### ISSUE TITLE
Update youtube version above 19.17.34

### ISSUE THREAD

**Issue by Astronxd** [ReVanced/revanced-manager#2248]
### Feature description

OnePlus update included youtube 19.17.34  on one of their OOS update and hence I cannot install revanced youtube replacing the original. I wont update oos for another year.

### Motivation

I am unable to use revanced manager due to this issue.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager.

**Comment by validcube** [comment]
👋 Hello, @njihil!

Thanks for filing this issue, but however this issue is out-of-scope for this repository (ReVanced Manager), the correct repository to file this issue in would be our [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches).

Your issue has been updated with list of acknowledgement that hadn't been met.
