### ISSUE TITLE
feat: Category for Patches in Revanced Manager

### ISSUE THREAD

**Issue by arichorn** [revanced/revanced-manager#303]
### Type

Functionality

### Issue

Because Revanced Manager lacks the ability to download YouTube/YTMusic/TikTok patches without knowing if the patches is rooted or non-rooted.

### Feature

In the patches on Revanced manager it should should show you texts next to each patch showing Non-Rooted patches and showing the Rooted patches, and hopefully add a category to check or uncheck the patches you prefer for your android device.

### Motivation

If this feature not considered to be in this then if a user like me tries to repack and build the apk, I would get a prompt saying to "Unable to install this on a Unrooted Device" or something which can be unbearably annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Categories are not possible because patches are arbitrary.

**Comment by arichorn** [comment]
Oh, it’s fine, maybe just put the texts of NON-ROOTED & ROOTED next to the versions, because if I install a patch that doesn’t work on Non-Rooted, I will probably have to wait a few hours to repack the apk again. Definitely needs it, forget the categorys anyways

**Comment by Hebgbs** [comment]
Mandate the patches declare if they require root. Because I am sort of hung up on this too — I would need to patch the application using _individual_ patches to figure out what can be done without root, and that sort of inconvenience is what's probably going to kill interest in the patcher for most people.

**Comment by oSumAtrIX** [comment]
All patches are compatible without root.

**Comment by Hebgbs** [comment]
Then how come there's this weird message telling me to try patches which doesn't require root when I install with all of the patches I want to use?

**Comment by Hebgbs** [comment]
If you give me a few minutes to upgrade the manager and attempt to patch YouTube with all of the mods I want on an LG G6 I have in my possession, I'll tell you _exactly_ what's going on.

**Comment by arichorn** [comment]
> All patches are compatible without root.

It isn’t for us. It’s saying to install it on a rooted device, I wouldn’t have requested this feature or bug if it didn’t tell me to only install with root.

**Comment by Hebgbs** [comment]
So here are the mods I am trying to install:
> Client Spoof
> Custom Branding
> Custom Playback Speed
> Custom Video Buffer
> Disable Auto Captions
> Downloads
> General Ads
> Hide Create Button
> Hide Shorts Button
> Hide Watermark
> Minimized Playback
> Remember Video Quality
> Return YouTUbe Dislike
> Seekbar Tapping
> Sponsorblock
> Video Ads
When I finish with the procedure and attempting to install the patched build of YouTube, I am greeted with this _lovely_ dialogue:
> _Non-root install is not possible with the current patches selection. Repatch your app or choose root install if you hve your device rooted._

That string wouldn't exist in the programme binary if this wasn't an issue fam. Even if the bubble colour for root patches was a different colour as a band-aid, it'd be a sore sight better than pissing around figuring out what patches I am using require root.

**Comment by arichorn** [comment]
That’s why I suggested them to add texts to each patch containing the words “ROOTED” or “NON-ROOTED which shows which one is which and would be able to install it without getting that “Non-Root install is not possible” message but either way they could probably made it a bug when updating the revanced manager.

**Comment by oSumAtrIX** [comment]
@Hebgbs The error message is missleading. All patches are available without root permissions. You simply require another patch, in addition, to allow running the app without root, regardless of the other patches. The patch you miss in question is `microg-support`. Due to the need for the manager to be agnostic to patches and the app it patches, the manager should not assume, that "you need `microg-support` to allow running the app without root. An example of this are patches such as for TikTok. TikTok does not require `microg-support`. That said, patches themselves can include some information such as the `microg-support` patch already does, more than that would interfere with the agnosticism of the manager towards the patches and the apps they target. Currently, the manager is not fully agnostic, but ideally would be.
