### ISSUE TITLE
bug: Cannot update patches v0.0.34

### ISSUE THREAD

**Issue by Valiceemo** [revanced/revanced-manager#411]
### Type

Other

### Bug description

Manager shows a patch update available for YouTube
Clicking info does nothing
YouTube does not show in installed patched apps

### Steps to reproduce

Open manager
See update
Unable to interact with it

### Android version

Android 12

### Manager version

0.0.34

### Target package name

YouTube 

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Update:

fix(youtube/video-ads): return empty ad list earlier oSumAtrlX

### Device logs (exported using Manager settings).

```shell
Manager does not allow saving logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by DymondZ** [comment]
Having exactly the same issue.

Revanced Manager does have the ability to export logs though.

Log output:
`--------- beginning of main
10-18 14:19:18.121 32172 32172 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-18 14:19:18.144 32172 32172 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10184; state: ENABLED
10-18 14:19:18.224 32172 32172 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
10-18 14:19:18.224 32172 32172 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
10-18 14:19:18.226 32172 32172 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-18 14:19:18.226 32172 32172 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: QUALCOMM build                   : c263890aed, Ifb496a9c37
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Build Date                       : 06/27/22
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.12
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Local Branch                     : 
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Remote Branch                    : 
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Remote Branch                    : 
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Reconstruct Branch               : 
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
10-18 14:19:18.314 32172 32172 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-18 14:19:18.321 32172 32172 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
10-18 14:19:18.758 32172 28446 I flutter : ReVanced API: Using CronetEngine + true
10-18 14:19:18.761 32172 28446 I flutter : ReVanced API: Using CronetEngine + true
10-18 14:19:18.774 32172 28460 W SQLiteLog: (28) double-quoted string literal: "0B1FF185ABD2EC1F352F76FABC54C393"
10-18 14:19:18.774 32172 28460 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-18 14:19:18.800 32172 32172 I DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:1611
10-18 14:19:18.800 32172 32172 I DynamiteModule: Selected remote version of com.google.android.gms.cronet_dynamite, version >= 1611
10-18 14:19:18.800 32172 32172 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
10-18 14:19:18.808 32172 32172 W System  : ClassLoader referenced unknown path: 
10-18 14:19:18.813 32172 28463 I DynamiteDebugLogger: [71] com.google.android.gms.cronet_dynamite
10-18 14:19:18.820 32172 32172 W manager.flutter: ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~5dkH3bX7kFSPCZtt9pTgRg==/app.revanced.manager.flutter-P3jPBnWm21cEkpS3TxBAAQ==/base.apk*4080718463:/data/app/~~5dkH3bX7kFSPCZtt9pTgRg==/app.revanced.manager.flutter-P3jPBnWm21cEkpS3TxBAAQ==/base.apk!classes2.dex*1824961251:/data/app/~~5dkH3bX7kFSPCZtt9pTgRg==/app.revanced.manager.flutter-P3jPBnWm21cEkpS3TxBAAQ==/base.apk!classes3.dex*78547179])
10-18 14:19:18.836 32172 32172 I cr_CronetLibraryLoader: Cronet version: 106.0.5249.23, arch: aarch64
10-18 14:19:19.395 32172 28447 I Gralloc4: Adding additional valid usage bits: 0x8202400
10-18 14:19:19.402 32172 28460 W SQLiteLog: (28) double-quoted string literal: "8384255B7F11AA240121190919F1B9E3"
10-18 14:19:19.402 32172 28460 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
10-18 14:19:19.415 32172 32172 E SurfaceSyncer: Failed to find sync for id=0
10-18 14:19:19.415 32172 32172 E SurfaceSyncer: Failed to find sync for id=1
10-18 14:19:19.422 32172 28440 W Parcel  : Expecting binder but got null!
10-18 14:19:20.315 32172 28460 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
10-18 14:19:20.315 32172 28460 W SQLiteLog: (28) double-quoted string literal: "98847AE9F1FB5E1705E333EED46BB7FC"
10-18 14:19:33.782 32172 28448 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: Error registering plugin root, com.gokul.root.RootPlugin
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: java.lang.IllegalStateException: The main shell was already created
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.internal.MainShell.setBuilder(MainShell.java:98)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.Shell.setDefaultBuilder(Shell.java:148)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at com.gokul.root.RootPlugin.onAttachedToEngine(RootPlugin.java:26)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:99)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine(MainActivity.kt:31)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8290)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8269)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1388)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:201)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:288)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
10-18 14:20:33.499 32172 32172 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-18 14:20:33.551 32172 29019 I flutter : ReVanced API: Using CronetEngine + true
10-18 14:20:33.552 32172 29019 I flutter : ReVanced API: Using CronetEngine + true
10-18 14:20:33.675 32172 29020 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2344 transform=0}
10-18 14:20:33.680 32172 32172 E SurfaceSyncer: Failed to find sync for id=0
10-18 14:20:33.680 32172 32172 E SurfaceSyncer: Failed to find sync for id=1
10-18 14:20:33.701 32172 28440 W Parcel  : Expecting binder but got null!
10-18 14:20:59.938 32172 32172 E SurfaceSyncer: Failed to find sync for id=0
10-18 14:20:59.938 32172 32172 E SurfaceSyncer: Failed to find sync for id=1
10-18 14:20:59.938 32172 32172 E SurfaceSyncer: Failed to find sync for id=2
`

**Comment by CnC-Robert** [comment]
Updating has been disabled as it doesn't work properly. To update you have to patch the stock apk

**Comment by Valiceemo** [comment]
yeah, i had to unstill the patched YT app, repatch and reinstall 
Now, for some reason, I cannot open the Manager
