### ISSUE TITLE
bug: Share APK feature not working

### ISSUE THREAD

**Issue by mewbow1** [revanced/revanced-manager#416]
### Type

Error while running the manager

### Bug description

After patching APK, when click on Reshare APK, it doesn't work.
But if we click Install button (non-root user) and then cancel install and click Reshare APK, it works. 

### Steps to reproduce

1. Patch any APK
2. Wait for patching to complete
3. Click on Share APK

### Android version

12

### Manager version

0.0.34

### Target package name

YouTube

### Target package version.

16.36.37

### Installation type

Non-root

### Patches selected.

Client Spoof, General Ads, Video Ads

### Device logs (exported using Manager settings).

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Hey! this issue is fixed in a recent commit but that commit has not been included in a release as of yet

It should be fixed in v0.0.35 when that comes out, in the meantime you have to click install first (you don't have to actually install the app, just click install and make sure the label at the top of the screen says Installed), you'll then be able to share the APK

**Comment by Ushie** [comment]
v0.0.35 should come out within the next few hours
