### ISSUE TITLE
feat: proper accessibility support

### ISSUE THREAD

**Issue by rootback123** [ReVanced/revanced-manager#514]
### Type

Functionality

### Issue

The app is very good it is functional with TalkBack but it can be improved more

### Feature

TalkBack support

### Motivation

The app works great with TalkBack but may improve support in the future,It is important for accessibility everyone needs and should and have the right to use any software.

### Additional context

The app works great with TalkBack but may improve support in the future, thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by rootback123** [comment]
As a visually impaired person, I think it's important to address this issue, I hope you understand. Thank you so much, I'm a fan of yours!

**Comment by rootback123** [comment]
I'm using a translator I'm a newbie guy but I hope I can help you

**Comment by rootback123** [comment]
Any news in the development of accessibility?

**Comment by atlasveldine** [comment]
I'm not visually impaired but am otherwise disabled and while TalkBack functionality is of little real importance to my own needs, I just thought I'd drop a comment to help illustrate the importance of accessibility features in apps.

When developers don't care about their user's accessibility needs (usually under the flawed basis that "only a small amount of people need this feature, so it shouldn't be high priority"), we end up with issues like Google removing the ability for apps to directly access logcat, crippling (word choice very much intentional) the functionality of countless automation and accessibility apps used by both those with accessibility needs due to disability as well as those without who simply used said apps for their fantastic features. In the past, it was fairly trivial to monitor a wide variety of device events - hardware buttons pushed, stuff like the SPen on Samsung devices, apps opening/closing, really the possibilities were endless - in order to react to these events programmatically. Now, though, it's extremely difficult, and for those who relied on such functionality, our lives became needlessly more difficult. Why did Google make this change? "Security."

In however many years, when your eyes are failing due to old age, I bet that you, too, will want to be able to continue to use your device, and for that reason alone you should always strive to make your apps as accessible as possible - if not for those who need it now then for your future self. If all dlvelopers thought this way, then in your old age, or should you ever get in an accident or grow ill, you'd still be able to use your devices without unnessecary struggle.

**Comment by Ushie** [comment]
What accessibility is missing from the application? The issue mentions that TalkBack works great and can be improved, but it doesn't specify how nor what's missing or needed

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
