### ISSUE TITLE
feat: process animation

### ISSUE THREAD

**Issue by Amby713** [revanced/revanced-manager#65]
### Type

Other

### Branch

While applying the patches, it looked like it stayed on the screen for a minute or two.

The progress bar was still in the same spot and no way of telling if it is still thinking/processing or if it timed out.

### Issue

Might cause people to think it's stuck/broken and force close the manger

### Feature

It'll give a status update indicator 

### Motivation

Because it'll serve everyone and reduce worries

**Comment by ponces** [comment]
Patching takes time in some cases.
Progress is there for some reason. A loading animation can also make the user to force close if it stays like that for several seconds.

And blocking for a minute or more is not an expected behaviour so once a new message does not arrive in max 30 seconds or so... it's already a pretty good indication that something went wrong.

Nevertheless, in the case that something fails, a crash or a indicator message should occur/appear.
