### ISSUE TITLE
bug: .env file can be viewed as plain text.

### ISSUE THREAD

**Issue by 2shrestha22** [revanced/revanced-manager#689]
### Type

Other

### Bug description

If anything is added as assets in pubspec.yaml it can be viewed as is. `flutter_dotenv` needs to have `.env` file as an assets that makes `.env` file readable as plain text on a compiled app (when extracted). We should not be using `flutter_dotenv` for storing API keys or credentials. 

### Steps to reproduce

Extract compiled apk you will find all assets including `.env` on `/assets/flutter_assets`.

### Android version

not required

### Manager version

not required

### Target package name

not required

### Target package version.

not required

### Installation type

Non-root

### Patches selected.

not required

### Device logs (exported using Manager settings).

```shell
not required
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheBITLINK** [comment]
I don't see an issue, first of all the only APIs the app accesses are the revanced API, which one can argue is public and read only to an extent, and the Sentry API, which is used mainly for error reporting and telemetry.

Those API keys need to be on the client one way or another, and even if they weren't in plaintext, would be very easy to extract via traffic sniffing or decompiling.

It would be a very different issue if there were sensitive API keys that should only be in the server and gave access to internal systems or critical infrastructure, but really, as client side keys, they could (and should) be considered public keys, and even if someone were to extract them, they couldn't do much more than can be done through the app itself (which in the case of revanced is just fetching the list of patches, and maybe submitting fake error reports?), but it does not pose additional risk, because as I mentioned, those API keys should be considered public and need to be in the client one way or another by design.

So yeah, I think the risk part is exagerated.

**Comment by Aunali321** [comment]
I know. I designed it that way. To be fair i didn't even need to make the env file, i could have just made it public. But i wanted avoid getting telemetry data from forks that don't change the api key.
