### ISSUE TITLE
bug: ReVanced Manager uses `patches.json` file from GitHub instead of API

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#807]
### Type

Error while running the manager

### Bug description

ReVanced Manager uses `patches.json` file from GitHub instead of API. This can cause a desync when the latest release is deleted because the app still relies on that releases `patches.json` file

### Manager version

0.0.57

### Installation type

Non-root

### Solution

Use the API to get the `patches.json` file, as the API relies on the releases completely.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
What makes you think that?

**Comment by oSumAtrIX** [comment]
Recently, a release (Z) has been deleted. Therefore the API has updated to the latest available release (Y). The branch itself remained untouched (Z). Yet ReVanced Manager was using the deleted release (Z). That means that it relied in the branches `patches.json` file instead of what the API supplied (Y).

**Comment by Axelen123** [comment]
It is the API that gets `patches.json` from the main branch, not manager.
![image](https://user-images.githubusercontent.com/28486288/233687675-8c111249-7899-475b-92c7-9322048c8aa2.png)
![image](https://user-images.githubusercontent.com/28486288/233687746-e4138807-e102-44e5-a42f-51b05380a468.png)

The reason why manager broke was because manager was getting the patch bundle from the latest release (either indirectly via releases API or directly via github API), but the patches endpoint of the API gets `patches.json` from the main branch, thus causing a desync when the patches repo CI cannot release a new version properly.

**Comment by oSumAtrIX** [comment]
I have checked the patches api and it did not return the main branches patches.json file but that of the latest release. Closing and moving issue to revanced/revanced-releases-api.
