### ISSUE TITLE
bug: microg patch disables root installer

### ISSUE THREAD

**Issue by Martinligabue** [revanced/revanced-manager#820]
### Type

Other

### Bug description

User session installer fails when installing yt microg version, root installer works, but from the app is disabled

### Steps to reproduce

use microg patch
click "install as root"

### Android version

12

### Manager version

0.0.57

### Target package name

com.google.android.youtube

### Target package version.

18.15.40

### Installation type

Non-root

### Patches selected.

microg

### Device logs (exported using Manager settings).

```shell
no crash, just blocked by app
```

### Solution

let users use root install if they really want to

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by eliyahillel** [comment]
I wouldn't necessarily consider this as a bug, but it is annoying because by default it's selected - and when I reset my manager or press the "select all recommended" - I have to remember to disable this before starting the patching process.

I personally think that there should be an option to set the default installation type in settings, and that way we can also get rid of the split-up install button

**Comment by Sanrax** [comment]
This is not a bug and intended behavior. You shouldn't be applying the MicroG patch if you want to use root, because the root version uses real GMS.
