### ISSUE TITLE
bug: Package conflicts when reinstalling as a full version after removing beta version

### ISSUE THREAD

**Issue by sssh7710** [revanced/revanced-manager#848]
### Type

Other

### Bug description

Package conflict occurs when reinstalling as a full version after removing beta version
Unusual Tablet Only Error

### Steps to reproduce

1. Uninstall an existing beta version of
2. Download version 0.0.57 and attempt to install
3. Package Conflict (Unable to resolve package file with same name with adb)

### Android version

android 13
One ui 5.1 

### Manager version

0.0.57

### Target package name

.

### Target package version.

.

### Installation type

Non-root

### Patches selected.

.

### Device logs (exported using Manager settings).

```shell
.
```

### Screenshots or videos

![Screenshot_20230505_115739_Package installer](https://user-images.githubusercontent.com/98168192/236369533-d7a2942b-a423-4d49-8805-b99b84a8f6f9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
This issue occurs as when the keystore got deleted along with the uninstallation of the app. That's why in the latest version there's an option to import or export keystore which will solve this issue from happening in the future. But in the current version of the manager once this occurs you'll have to uninstall all existing ReVanced apps and reinstall them inorder to avoid the conflicts.
