### ISSUE TITLE
Change Package name feature request

### ISSUE THREAD

**Issue by karthikvijay5227** [revanced/revanced-manager#974]
### Type

Functionality

### Issue

I am eagerly waiting for the feature of changing package name as I want to patch YouTube and I can't able to installed it doe to package conflict.It need to be solved.

### Feature

Changing package name

### Motivation

For patching youtube

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Julius8900** [comment]
You can change the package name using CLI.

**Comment by karthikvijay5227** [comment]
How to change using cli can you give the steps.

**Comment by Julius8900** [comment]
https://github.com/revanced/revanced-cli/tree/main/docs

**Comment by karthikvijay5227** [comment]
Is it not possible to integrate in android app.Cli method seems complex and
also it doesn't giving support for splitted apks

**Comment by oSumAtrIX** [comment]
Yes, it is possible to integrate into ReVanced Manager. ReVanced CLI is not complex and does five support for split APK files, the same way ReVanced Manager does.

**Comment by karthikvijay5227** [comment]
I want the feature of changing package name in revanced app not in cli.Hope
it will appear in the next update.It is not available for me till now.

**Comment by Gigahawk** [comment]
I don't know why this was closed as completed, it appears to be a duplicate of #909.

This is an issue tracker specifically for the revanced manager app, not the project as a whole.
"Use the cli" is not a valid response to the app not supporting a particular feature.

**Comment by oSumAtrIX** [comment]
The issue was closed because it's regarding a patch and not ReVanced Manager.

**Comment by YoussF** [comment]
Any news about this feature ?

**Comment by qguv** [comment]
> https://github.com/revanced/revanced-cli/tree/main/docs

@Julius8900 The link you provide to the front page of the docs for the ReVanced CLI project doesn't actually answer @karthikvijay5227 's question. I found this issue while trying to accomplish the same thing (modify the package name of an APK) and couldn't find anything in the docs which addresses that.

Besides this, it seems like the appropriate response to this user's wish to change the package name of an APK from the Android app directly would be to treat the issue as a _feature request_ to add this functionality to the Android app, rather than dismissing it as an issue regarding a particular patch and closing their issue.

If you want want to implement it, fine, but it's certainly not offtopic :)
